name: novel-recommendation-env
# 显式配置通道，优先清华源加速，包含 defaults 避免警告
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  # 基础依赖
  - python=3.11
  - pip
  # 核心依赖（根据项目需求调整版本）
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scikit-surprise>=1.1.0
  - streamlit>=1.10.0
  - joblib>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  # pip 补充（如果有 Conda 装不了的包）
  - pip:
      # 示例：如果需要额外 pip 包，加在这里
      # - some-package==x.x.x
      --index-url https://pypi.tuna.tsinghua.edu.cn/simple  # pip 清华源加速
