name: novel-recommendation-env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/  # conda-forge 清华源
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/        # 免费包清华源
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/         # main 通道清华源
  - defaults  # 保留 defaults 兜底（可选，也可去掉，优先用清华源）
dependencies:
  - python=3.11  
  - pandas>=1.3.0  
  - numpy>=1.21.0  
  - scikit-surprise>=1.1.0  
  - streamlit>=1.10.0  
  - joblib>=1.1.0  
  - matplotlib>=3.5.0  
  - seaborn>=0.11.0  